### ISSUE TITLE
how do I install the package?

### ISSUE THREAD

**Issue by matthewcornell** [aws/amazon-ec2-utils#21]
Hi Folks. I'm a relatively new EC2/AWS user, and I arrived here by way of wanting to get the latest version of your package. (The Amazon Linux 2 AMI has v0.1.2 of ec2-metadata installed, and I'd like to get the tags support you've added. In fact, I'm pretty surprised that this package is so out of date on Amazon's own OS!) Anyway, I want to install it on my instance but I do not see instructions in the readme, nor do I see a makefile. Thanks for your kind help!

**Comment by matthewcornell** [comment]
I decided to simply replace the `/usr/bin/ec2-metadata` file I have with [the version in this repo](https://github.com/aws/amazon-ec2-utils/blob/main/ec2-metadata). Note that it still says v0.1.2. Thanks.

**Comment by nmeyerhans** [comment]
Hi @matthewcornell As you've noticed, the versions here aren't necessarily consistent with the versions in Amazon Linux. The ec2-utils 1.2-45 package in Amazon Linux 2 corresponds with the 1.4 release here, though I hope to bring the releases into sync before too long. Note that Amazon Linux 2022 (currently in preview) is more consistent, with its 2.0 packages based on the 2.0 release here.

As to the specific question about tags retrieval via `ec2-metadata`, the Amazon Linux 2 release schedule is independent of this project's schedule, and it ingests upstream changes on its own timeline. It will incorporate the new feature, but I can't make any promises about exactly when.
