### ISSUE TITLE
ebsnvme-id and udev rule fails due to Syntax Error of print() on line 167

### ISSUE THREAD

**Issue by diablodale** [aws/amazon-ec2-utils#4]
Hi. After a `yum` upgrade triggered by security updates, my AWS Linux 2 (amzn2-ami-ecs-hvm-2.0.20191212-x86_64-ebs) instance's containers failed to start.
I traced the problem to a failure of udev rules to create an alias for EBS volumes that appear as NVMe drives.
Which then led me to find the `ebsnvme-id` tool installed in this yum package is failing.

https://github.com/aws/amazon-ec2-utils/blob/3cd27a273407d4aeadc9b330a463686c0e71f4d5/ebsnvme-id#L167

That line, to my knowledge is invalid syntax. Python 2.7.18 is the default python on Amazon Linux2 AMI and its standard stream of yum updates. If one tries to run this `ebsnvme-id` tool by hand, this is the result:

```
[myprompt]# /sbin/ebsnvme-id
  File "/sbin/ebsnvme-id", line 167
    print(err, file=sys.stderr)
                   ^
SyntaxError: invalid syntax
```

And when one runs it like the official AMI installed udev rule `/etc/udev/rules.d/70-ec2-nvme-devices.rules`, it also fails, and therefore the udev rule fails, so the alias isn't made, leading to a cascade of volume failures

```
[myprompt]# /sbin/ebsnvme-id -u /dev/nvme1n1
  File "/sbin/ebsnvme-id", line 167
    print(err, file=sys.stderr)
                   ^
SyntaxError: invalid syntax
```

Referencing the official Python 2.7 docs https://docs.python.org/2/reference/simple_stmts.html#the-print-statement
the print statement does not support that syntax.

Only Python 3 supports a `file=` on the print() statement. And since Python 2.7.18 is the official default python of the AWS Linux 2 AMI, and the top of this python file `#!/usr/bin/env python` doesn't specific a version, that means this file is trying to use Python3 language features on Python2. Therefore, python won't run it, and a cascade of failures occur.

**Comment by diablodale** [comment]
Looks to be due to this commit https://github.com/aws/amazon-ec2-utils/commit/162db13ecfd5c9a34b2fa46e5dc6fe5cef6dbeb5#diff-f23d0c1e2d05912060ebafb0bc0393104f9153613b6ec8cd51a57ce0a17575b8

AmazonLinux2 AMI does not install or use python3 as standard system python
https://forums.aws.amazon.com/thread.jspa?threadID=312472

> There are no plans to change the default Python interpreter. It is our intention to retain Python 2.7 as the default for the lifetime of Amazon Linux 2.

**Comment by tms** [comment]
`yum downgrade ec2-utils` from 1.2-2 to 1.2-1 seemingly reverts to before the change in question, which raises some questions about the package versioning, heh

**Comment by djarnis73** [comment]
It seems like 1.2-3 was released which looks like resolves this issue.

**Comment by diablodale** [comment]
Hi @fred-lefebvre, I see you made a commit somewhere that was also put into this repo. Glad to see it was fixed.
Is this repo to be used for issues? If so, would you please have someone engage with us and/or close issues as you fix them.
My intention is to understand if this is a dead repo, actively monitored (which doesn't seem to be), etc.

**Comment by nmeyerhans** [comment]
@diablodale This repo is a reasonable place for issues/pull requests/etc. It is monitored, although you've likely noticed that it's not the most active repo in the world at this point. Feel free to highlight @nmeyerhans or @fred-lefebvre in any issues to increase the likelihood of us notice it among all the other activity going on.

The problem originally brought up with this issue has long since been resolved, and with my recent addition of Circle CI configuration (#12), we should avoid a recurrence of similar issues.
